- hosts: all
  remote_user: "{{ newuser }}"
  sudo: yes
  vars_files:
    - vars.yml
  roles:
    - docker
    - swap
    - { role: docker_build, service: mysql, tags: [], exec_files: ['backup.sh', 'load_db.sh'] }
    - { role: docker_build, service: php, tags: [], exec_files: [] }
    - { role: docker_build, service: backend, tags: ['backend'], exec_files: ['site-normal', 'site-upgrade', 'site-upgrade', 'start-nginx.sh'] }
    - { role: docker_build, service: varnish, tags: [], exec_files: ['start-varnish.sh'] }
    - { role: docker_build, service: frontend, tags: [], exec_files: ['start-nginx.sh'] }
    - wordpress
    - new_wordpress
  tasks:
    - { include: tasks/docker-compose_rebuild.yml, service: data, tags: [] }
    - { include: tasks/docker-compose_rebuild.yml, service: frontend, tags: [] }
    - { include: tasks/docker-compose_rebuild.yml, service: varnish, tags: ['backend'] }
    - { include: tasks/docker-compose_rebuild.yml, service: backend, tags: ['backend'] }
    - { include: tasks/docker-compose_rebuild.yml, service: php, tags: [] }
    - { include: tasks/docker-compose_rebuild.yml, service: mysql, tags: [] }
    #remove the workpress install not in the container
    #bring up the containers and remove any unused containers
    - { include: tasks/docker_up.yml }

    - name: Set permissions in container
      shell: "{{ work_dir }}/site-normal"
